# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AtuWE41-GZoCjfIK7w5AazebXPXX9UDU
"""

!pip install -U langchain-openai
import requests
from bs4 import BeautifulSoup
def extract_text_from_url(url):
  response = requests.get(url)
  if response.status_code == 200:
    soup = BeautifulSoup(response.text, "html.parser")
    for script_or_style in soup(['script', 'style']):
      script_or_style.extract()
    text = soup.get_text()
    # Clean the text: remove extra newlines and strip whitespace
    clean_text = '\n'.join(line.strip() for line in text.splitlines() if line.strip())
    return clean_text
  else:
    print(f"Failed to fetch the URL. Status code: {response.status_code}")
    return None

extract_text_from_url("https://dev.to/kenakamu/azure-open-ai-in-vnet-3alo")

from langchain_openai.chat_models.azure import AzureChatOpenAI


client = AzureChatOpenAI(
    azure_endpoint = "https://oai-dio-bootcamp-dev-eastus-002-deonni.openai.azure.com/",
    api_key="eyydw6tDnETJj2SneGIeGk69TJKFcQAl73ZvRXSmUjEGbBLgAljWJQQJ99CAACHYHv6XJ3w3AAABACOGaU25",
    api_version="2024-02-15-preview",
    deployment_name="gpt-4o-mini",
    max_retries=0
)

def translate_article(text,lang):
  messages=[("system" , "Você atua como tradutor de textos"),
            ("user",f"traduza o {text} para o idioma {lang} e responda em markdown")
           ]
  response =client.invoke(messages)
  print(response.content)
  return response.content

translate_article("Let´s see if the deployment was suceeded","portugues")

url = "https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design"
text= extract_text_from_url(url)
article = translate_article (text,"pt-br")
print(article)